# Parameters for the magnetic field -------------------------------------------
[field]

# Fraction of magnetic energy that is in the turbulent field
turb_ener_frac = 0.0
# Spectral index of turbulence
spectral_index = 1.666666666666666
# Largest turbulent wavelength
max_wave = 10.0
# Smallest turbulent wavelength
min_wave = 0.1
# Resolution factor for wavelengths
# -- waves = <wave_resolution> log10(<max_wave> / <min_wave>)
wave_resolution = 50
# Wave speed
# -- Assumed to be the Alfven speed of the ambient medium
wave_speed = 1.0e-3

# Parameters for the experiment -----------------------------------------------
[ experiment ]

# Name of the experiment
name = "eta_0.00"
# Notes regarding the experiment
notes = "notes"
# Evolve particles until max_time (lab-frame time, not proper time)
max_time = 2e4
# Total number of test particles
number_of_particles = 10
# RNG seed for particle initialization
# -- each particle uses <particle_seed> + <particle_id> as seed
particle_seed = 1
# Total number of field realizations
number_of_fields = 1000
# RNG seed for magnetic field initialization
# -- each field uses <field_seed> + <field_id> as seed
field_seed = 1
# Directory in which to save results
experiment_directory = "eta_000"
# Stub for subdirectory containing all results from a given field
field_stub = "field_"
# Stub for particle trajectory files
particle_stub = "trajectory_"
# Time step "small" factor: should be no greater than ~1/20
step_small = 0.05
# Maximum number of steps allowed per trajectory
max_steps = 99999999
